name: airbash-frontend build pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.5.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Fetch
        run: git fetch --no-tags --prune --depth=5 origin master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm run install --legacy-peer-deps
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      #- name: Run end to end tests
      #run: npm run e2e
      - name: Build
        run: npm run build
